name: Auto Blogger Post

on:
  schedule:
    - cron: '0 6 * * *'   # 6 AM UTC
    - cron: '0 18 * * *'  # 6 PM UTC
  workflow_dispatch:

jobs:
  post-to-blogger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-api-python-client requests

    - name: Run Blogger AI Poster
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: python blogger_ai_poster.py
